version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always

  scraper:
    container_name: scraper
    image: scraper
    restart: "no"
    build:
      context: .
