version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - mongodb:/data/db

  scraper:
    container_name: scraper
    image: scraper
    restart: "no"
    build:
      context: .

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --include-restarting --schedule "0 * * * *"

volumes:
  mongodb:
